name: main_page
description: Main Page Module.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  core:
    path: ../core
  dependencies:
    path: ../dependencies
  art_core:
    path: ../art_core
  dashboard:
    path: ../dashboard
  services:
    path: ../services

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.0

flutter:

  uses-material-design: true
